### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by vuxor** [nlukic97/zadatak_6#3]
https://github.com/nlukic97/zadatak_6/blob/aec7c0042640121d94056c5cfd5ad72fe3f060ce/public/js/script.js#L94-L106
Can you use [this](https://github.com/nlukic97/zadatak_6/blob/master/public/js/script.js) for smooth scrolling?

**Comment by nlukic97** [comment]
[Link text Here](https://github.com/nlukic97/zadatak_6/pull/4/commits/a9312a4ae6ad26d9de2d5aeb9adb9b25f7a8000a) should fix it
